name: t21-thurs-harmonica
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - pip
  - harmonica
  - pooch
  - matplotlib
  - pandas
  - numba
  - xarray
  - pyproj
  - jupyterlab
